name: Build Main

on:
  push:
    branches:
      - main


jobs:
  build-sources:
    name: Build the source code
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Build
        run: msbuild avatar-mod-winrt.vcxproj -t:rebuild -property:Configuration=Debug -interactive:False -nologo